stages:
  - test

trigger-multiproject:
  image: node:14-alpine
  tags:
    - docker
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_PIPELINE_SOURCE == "trigger"
  script:
    - apk update && apk add curl
    # The token is project-specific, and only works for that group's test repo.
    - 'curl --request POST --form token=$YOUR_TOKEN --form ref=main "https://git.chalmers.se/api/v4/projects/courses%2Fdit345%2F2023%2Ftests%2Fa4-group-${CI_PROJECT_NAME:9:2}-test/trigger/pipeline"' 
  #environment: production
  #trigger:
  #  project: $PATH